Support hooking instructions
frida/frida-rust pull request #56
Opened 2022-08-22 09:32 UTC by talliberman

2022-08-25 07:15 UTC, talliberman commented
Hi @meme, 

I tried to figure out why the CI failed and noticed that `cargo test` seems to fail on the main branch as well.

2022-08-26 19:54 UTC, meme commented
Firstly, it's not clear why all this extra code is needed if the only functional difference is having on_leave set to NULL. Is it possible to instead change the C API for `GumRustInvocationListener` to support both modes of operation? Then we can reuse the existing code path.

> I tried to figure out why the CI failed and noticed that cargo test seems to fail on the main branch as well.

Seems like Rust stable 1.63.0 introduced a change which breaks our pipeline with a new error for `reference to packed field is unaligned`. I'll fix this in `main` so you can rebase. It seems that there are some duplicated symbol errors for your PR as well, though (same names in `instruction_invocation_listener.c` as `invocation_listener.c`)

2022-08-28 15:54 UTC, talliberman commented
Thanks for your reply.

>  Firstly, it's not clear why all this extra code is needed if the only functional difference is having on_leave set to NULL. Is it possible to instead change the C API for GumRustInvocationListener to support both modes of operation? Then we can reuse the existing code path.

It may be possible but I couldn't find an easy way to reuse the code. If you know how it can be done let me know and I could implement it differently. If we want to reuse the code in `invocation_listener.c` the main hurdle is that the flag which indicates whether we are hooking a function with on_enter/on_leave or a specific instruction needs to be passed to the function `gum_rust_invocation_listener_iface_init` so that it can set `iface->on_leave = NULL`.

I took a look at Frida's implementation in `gum/guminvocationlistener.c`. It seems they implemented two different `GumInvocationListener`s: `GumCallListener` and `GumProbeListener`. Which is quite similar to my implementation.

> Seems like Rust stable 1.63.0 introduced a change which breaks our pipeline with a new error for reference to packed field is unaligned. I'll fix this in main so you can rebase. It seems that there are some duplicated symbol errors for your PR as well, though (same names in instruction_invocation_listener.c as invocation_listener.c)

Great thanks, when the main branch is fixed I will rebase and fix any errors that I added.

2022-08-29 22:10 UTC, meme commented
> It may be possible but I couldn't find an easy way to reuse the code

Apologies if I am misunderstanding, but is it not as simple as replacing `instruction_invocation_listener_transform` with:

```rust
pub(crate) fn instruction_invocation_listener_transform<I: InstructionInvocationListener>(
    invocation_listener: &mut I,
) -> *mut frida_gum_sys::GumInvocationListener {
    let rust = frida_gum_sys::RustInvocationListenerVTable {
        user_data: invocation_listener as *mut _ as *mut c_void,
        on_enter: Some(call_on_enter::<I>),
        on_leave: None, // <--- Use None instead of setting the 
    };

    unsafe { frida_gum_sys::gum_rust_invocation_listener_new(rust) }
}
```

Which makes `on_leave` NULL without duplicating the code?

2022-08-30 07:49 UTC, talliberman commented
I assumed (because of [this](https://github.com/frida/frida-gum/issues/445)) that we must set `iface->on_leave = NULL` in `gum_rust_invocation_listener_iface_init`, but it seems like setting it to `gum_rust_invocation_listener_on_leave` and not calling the rust callback if it's `NULL` inside of `gum_rust_invocation_listener_on_leave` works as well.

I implemented it that way and pushed.

2022-08-30 21:32 UTC, meme requested changes
Few nits. Other than that LGTM. Thanks for the PR.

2022-08-30 21:32 UTC, meme commented on frida-gum-sys/invocation_listener.c
> +  if (NULL != self->rust.on_leave){
```suggestion
  if (NULL != self->rust.on_leave) {
```

2022-08-30 21:32 UTC, meme commented on frida-gum/src/interceptor.rs
> +        f: NativePointer,
```suggestion
        instr: NativePointer,
```

2022-08-30 23:08 UTC, oleavr commented
I'm afraid the GObject interface `on_leave` must be `NULL`, otherwise `Interceptor` is going to replace the return address/LR and that will result in undefined behavior when the instruction selected isn't the first instruction of a function. So while it may appear to work, it's going to result in corruption in many cases.

2022-08-31 04:02 UTC, talliberman commented
Thanks for your input @oleavr. Would you say that the implementation in 255a6bcfeee9b89059515d6cc18dea4e793e00a2 is OK?

Also, where is the code that skips the instrumentation of the return address/LR if `on_leave` is `NULL`?

2022-09-04 05:19 UTC, talliberman commented
I brought back the implementation with a separate listener. I renamed `InstructionInvocationListener` -> `ProbeListener` as that is more consistent with the implementation in `Frida`.

2022-09-04 05:40 UTC, talliberman commented on frida-gum/src/interceptor.rs
> +        f: NativePointer,
Fixed

2022-09-04 14:33 UTC, meme requested changes

2022-09-04 14:33 UTC, meme commented on frida-gum-sys/build.rs
> +            builder
```suggestion
        builder
```

2022-09-04 17:23 UTC, talliberman commented
The failure in the CI is the same as #58

2022-09-04 20:10 UTC, talliberman commented
I can't reproduce the issue from the CI, but I pushed an attempt to fix it.

2022-09-06 00:26 UTC, meme approved these changes
Sorry for the back-and-forth on this! LGTM.

2022-09-06 00:27 UTC, merged